### ISSUE TITLE
Provide compiled binaries or detailed build instructions

### ISSUE THREAD

**Issue by fcastilloec** [Comcast/Infinite-File-Curtailer#6]
I found this through a post on Stack Exchange, the premise looks amazing, but I'm showing various errors when compiling the code. Here's the error:

> crtl_private.h:43:94: error: format ‘%llu’ expects argument of type ‘long long unsigned int’, but argument 4 has type ‘uint64_t {aka long unsigned int}’ [-Werror=format=]

Given my limited knowledge on how to compile, and even less knowledge on what the code actually does, I would greatly appreciate if you can just provide a binary that we can just use.

**Comment by dwolaver** [comment]
Hi Felipe,

I hope to get the program available for installation common platforms in the near future.  What Linux version are you running on?

I'll provide a fix to the compile error.

-Dave

**Comment by dwolaver** [comment]
Compile errors are fixed in latest revision.  I was able to compile/install in ubuntu 18 using the following commands:

autoreconf -i
sudo sh configure --prefix /usr/local
sudo make install

Let me know how it goes...

-Dave

**Comment by fcastilloec** [comment]
I'm using Ubuntu 18.04. I just pull your latest changes and it's working now. I still rather wait for a release from you before I start using this tool officially, in the meantime I'll play with it and get familiar with it.
Have you considered setting up a CI (i.e. Travis) that could build and publish a new release to GitHub?

**Comment by dwolaver** [comment]
Great!  I'm in the process of getting it included in debian so users can install via apt/yum/etc, but I expect that to take a while.  I'll investigate a way to publish binaries as you suggest for popular distributions.

**Comment by peterbmckinley** [comment]
Hi I'd love to use this but I'm baffled.

My command sends streaming data from a usb GPS device to a log file, set to append.

cat /dev/ttyACM0 >> log.txt

I just want to limit the file size, but keep it overwriting.

I think Curtail can do it, but I can't work out the command. I THINK it compiled ok

Thanks in advance, Peter

**Comment by dwolaver** [comment]
> 
> 
> Hi I'd love to use this but I'm baffled.
> 
> My command sends streaming data from a usb GPS device to a log file, set to append.
> 
> cat /dev/ttyACM0 >> log.txt
> 
> I just want to limit the file size, but keep it overwriting.
> 
> I think Curtail can do it, but I can't work out the command. I THINK it compiled ok
> 
> Thanks in advance, Peter

Hi Peter,

The general usage would be...

cat /dev/ttyACM0 | curtail -s 2M log.txt

You'll have to read the tty in a loop to wake up when more data has arrived.

Hope this helps! -Dave

**Comment by peterbmckinley** [comment]
Hi Dave,
It was fine, till I rebooted. Now instead of running it just goes back to the command prompt:

peter@peter-powermatemlxxx:~$ cat /dev/ttyACM0 | curtail -s 20k log.txt
crtl_cmdline_args: log level <INFO>
crtl_cmdline_args: output file size <20480>
crtl_cmdline_args: output file path <log.txt>
crtl_main_init: logical block size 4096 bytes
crtl_main_init: current file size 20393 bytes
peter@peter-powermatemlxxx:~$ 

I tried compiling again, but it made no difference. I deleted the existing log.txt file, still the same problem.

What did I do wrong?

Peter

**Comment by peterbmckinley** [comment]
Hi Dave,

Ignore my last message, replugging the usb gps dongle did the trick, its been fine now, even after several reboots.

Good work. Any luck getting it adopted in Debian?

Peter

**Comment by dwolaver** [comment]
Glad you're able to sort out the issue.  I haven't followed up with Debian recently.  Still hope to get this accomplished at some point...

**Comment by peterbmckinley** [comment]
Hi Dave,

Excuse my lack of knowledge about Linux, but how would you recommend amending the command to automatically compress the log file? My application is effectively a datalogger, and I want to optimise the period of time the log can cover in terms of the available storage (100 MB). Accessing the log will be via Windows, so a standard Windows compatible Zip file would be preferable, although 7zip is definitely an option. Hopefully if you have an idea to include compression in your command, you could add that to your usage readme.

I think your Curtail deserves formal uptake, logrotate was way beyond me!

Rgds, Peter

**Comment by peterbmckinley** [comment]
I think gzlog probably has the answer, but configuring it is beyond me...

https://github.com/madler/zlib/blob/master/examples/gzlog.c

Peter
