### ISSUE TITLE
Cant install

### ISSUE THREAD

**Issue by scascalesp** [Comcast/Infinite-File-Curtailer#7]
Hello

Error:
root@kysnas:/var/log#  apt-get install -y curtail
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package curtail

--

Then i install autotools: https://askubuntu.com/questions/430706/installing-autotools-autoconf-on-ubuntu
Error:
root@kysnas:/mnt/data/Infinite-File-Curtailer-master# libtoolize
-bash: libtoolize: command not found

Thx

**Comment by OttomanZ** [comment]
@scascalesp You can go ahead and do the following

```bash
sudo apt install libtool && sudo apt install automake && sudo apt install autoconf
```

Then copy paste and run the following in your Linux Terminal:
```bash
libtoolize
aclocal
autoheader
autoconf
automake --add-missing
./configure
make
```
Then using sudo do:
```
sudo make install
```
Hope that helps :+1:  worked for me.

**Comment by OttomanZ** [comment]
@Comcast add the following updated guide to the `README.md` tested on Pop_OS Latest build as of Feb, 12, 2023.

**Comment by dwolaver** [comment]
Thanks for the feedback.  The readme has been updated accordingly.
